image: telestoworld/ci-node:12

build:
  only:
    - master
    - staging
    - release
  script:
    - cd status && yarn install && PUBLIC_URL=https://catalysts.telesto.world yarn build && cd ..
    - tcl-lock-sync
    - cd .ci && npm install && tcl-up website-catalysts
    - tcl-sync-release && cd ..
    - tcl-upload status/build
    - cd .ci && tcl-cache-invalidation
